version: '3.3'

services:
  db:
    container_name: "mxtilet_db"
    image: mysql:5.7
    volumes:
      - db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - network_mixtoilet

  wordpress:
    container_name: "mxtilet_wordpress"
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - ../wordpress:/var/www/html
    ports:
      - "8080:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    networks:
      - network_mixtoilet
  
  phpmyadmin:
    container_name: "mxtilet_phpmyadmin"
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 9000:80
    depends_on:
      - db
    networks:
      - network_mixtoilet

volumes:
    db:

networks:
  network_mixtoilet:
    external: true